apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: busybox-alpine
      image: alpine:latest
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]